In [76]:
import  tensorflow as tf

In [77]:
import pandas as pd

In [78]:
df=pd.read_csv("../../data/NIFTY 50 and bank nifty -13-05-2023-to-13-05-2024.csv")

In [79]:
df.head()

Date  Nifty50_Open   Nifty50_High  Nifty50_Low  Nifty50_Close  \
0  15-May-23       18339.30      18458.90     18287.90       18398.85   
1  16-May-23       18432.35      18432.35     18264.35       18286.50   
2  17-May-23       18300.45      18309.00     18115.35       18181.75   
3  18-May-23       18287.50      18297.20     18104.85       18129.95   
4  19-May-23       18186.15      18218.10     18060.40       18203.40   

   Nifty50_Shares Traded  Nifty50_Turnover (? Cr)  Bank_Open   Bank_High   \
0              216088535                 19329.75    43821.05    44151.70   
1              219490491                 21063.78    44144.15    44144.15   
2              229898510                 20903.12    43948.50    43992.75   
3              272103515                 24172.44    44006.90    44079.20   
4              260898407                 22105.67    43930.00    44020.90   

   Bank_Low  ...  Next_Nifty50_Low  Next_Nifty50_Close  \
0   43666.6  ...          18264.35            18286.50   
1   43815.7  ...          18115.35            18181.75   
2   43446.4  ...          18104.85            18129.95   
3   43673.7  ...          18060.40            18203.40   
4   43531.9  ...          18178.85            18314.40   

   Next_Nifty50_Shares Traded Next_Nifty50_Turnover (? Cr)  Next_Bank_Open   \
0                   219490491                     21063.78         44144.15   
1                   229898510                     20903.12         43948.50   
2                   272103515                     24172.44         44006.90   
3                   260898407                     22105.67         43930.00   
4                   262560942                     25147.58         43935.30   

   Next_Bank_High   Next_Bank_Low  Next_Bank_Close  Next_Bank_Shares Traded  \
0         44144.15        43815.7          43903.7                222536217   
1         43992.75        43446.4          43698.7                203597921   
2         44079.20        43673.7          43752.3                226492176   
3         44020.90        43531.9          43969.4                192042449   
4         44026.75        43684.9          43885.1                183783537   

   Next_Bank_Turnover (? Cr)  
0                   10093.99  
1                    9812.19  
2                   12657.89  
3                    9384.53  
4                    8083.39  

[5 rows x 26 columns]

In [80]:
df.isna().sum()

Date                            0
Nifty50_Open                    0
Nifty50_High                    0
Nifty50_Low                     0
Nifty50_Close                   0
Nifty50_Shares Traded           0
Nifty50_Turnover (? Cr)         0
Bank_Open                       0
Bank_High                       0
Bank_Low                        0
Bank_Close                      0
Bank_Shares Traded              0
Bank_Turnover (? Cr)            0
Next_Date                       0
Next_Nifty50_Open               0
Next_Nifty50_High               0
Next_Nifty50_Low                0
Next_Nifty50_Close              0
Next_Nifty50_Shares Traded      0
Next_Nifty50_Turnover (? Cr)    0
Next_Bank_Open                  0
Next_Bank_High                  0
Next_Bank_Low                   0
Next_Bank_Close                 0
Next_Bank_Shares Traded         0
Next_Bank_Turnover (? Cr)       0
dtype: int64

In [81]:
df=df.dropna()

In [82]:
df.isna().sum()

Date                            0
Nifty50_Open                    0
Nifty50_High                    0
Nifty50_Low                     0
Nifty50_Close                   0
Nifty50_Shares Traded           0
Nifty50_Turnover (? Cr)         0
Bank_Open                       0
Bank_High                       0
Bank_Low                        0
Bank_Close                      0
Bank_Shares Traded              0
Bank_Turnover (? Cr)            0
Next_Date                       0
Next_Nifty50_Open               0
Next_Nifty50_High               0
Next_Nifty50_Low                0
Next_Nifty50_Close              0
Next_Nifty50_Shares Traded      0
Next_Nifty50_Turnover (? Cr)    0
Next_Bank_Open                  0
Next_Bank_High                  0
Next_Bank_Low                   0
Next_Bank_Close                 0
Next_Bank_Shares Traded         0
Next_Bank_Turnover (? Cr)       0
dtype: int64

In [83]:
from sklearn.preprocessing import MinMaxScaler

In [84]:
scaler = MinMaxScaler()

In [85]:
m1=tf.keras.Sequential(
    [
        tf.keras.layers.Dense(8, activation='relu'),
        tf.keras.layers.Dense(6, activation='relu'),
        tf.keras.layers.Dense(6, activation='relu'),
        tf.keras.layers.Dense(4, activation='sigmoid')
    ]
)
m1.build(input_shape=12)

In [86]:
m1.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [87]:
m1.compile(
    optimizer='adam',
    loss=tf.keras.losses.MeanAbsoluteError(
    reduction='sum_over_batch_size',
    name='mean_absolute_error'
),
    metrics=['accuracy']    
)

In [88]:
df.columns

Index(['Date', 'Nifty50_Open ', 'Nifty50_High', 'Nifty50_Low', 'Nifty50_Close',
       'Nifty50_Shares Traded', 'Nifty50_Turnover (? Cr)', 'Bank_Open ',
       'Bank_High ', 'Bank_Low', 'Bank_Close', 'Bank_Shares Traded',
       'Bank_Turnover (? Cr)', 'Next_Date', 'Next_Nifty50_Open ',
       'Next_Nifty50_High', 'Next_Nifty50_Low', 'Next_Nifty50_Close',
       'Next_Nifty50_Shares Traded', 'Next_Nifty50_Turnover (? Cr)',
       'Next_Bank_Open ', 'Next_Bank_High ', 'Next_Bank_Low',
       'Next_Bank_Close', 'Next_Bank_Shares Traded',
       'Next_Bank_Turnover (? Cr)'],
      dtype='object')

In [89]:
trainx_y_col=df.columns[20:24]
trainx_y_col
trainx_x_col=df.columns[1:13]
trainx_x_col

Index(['Nifty50_Open ', 'Nifty50_High', 'Nifty50_Low', 'Nifty50_Close',
       'Nifty50_Shares Traded', 'Nifty50_Turnover (? Cr)', 'Bank_Open ',
       'Bank_High ', 'Bank_Low', 'Bank_Close', 'Bank_Shares Traded',
       'Bank_Turnover (? Cr)'],
      dtype='object')

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
x_train, x_test, y_train, y_test = train_test_split(df[trainx_x_col], df[trainx_y_col], test_size= 0.2, random_state= 1)

In [92]:
x_train

Nifty50_Open   Nifty50_High  Nifty50_Low  Nifty50_Close  \
169       22080.50      22124.15     21969.80       22032.30   
159       21751.35      21755.60     21555.65       21665.80   
180       21780.65      21832.95     21658.75       21697.45   
147       21110.40      21210.90     21074.45       21182.70   
150       21477.65      21505.05     21337.75       21453.10   
..             ...           ...          ...            ...   
137       20108.50      20158.70     20015.85       20133.15   
72        19297.40      19339.55     19229.70       19265.80   
140       20808.90      20864.05     20711.15       20855.10   
235       22421.55      22476.45     22384.00       22402.40   
37        19385.70      19512.20     19373.00       19497.30   

     Nifty50_Shares Traded  Nifty50_Turnover (? Cr)  Bank_Open   Bank_High   \
169              292433764                 24435.94    48109.95    48305.40   
159              263711568                 25316.13    48194.80    48223.55   
180              332541208                 34042.15    46164.90    46306.90   
147              334410589                 32593.42    47567.65    47943.60   
150              249750062                 23750.61    47940.40    48017.00   
..                     ...                      ...         ...         ...   
137              486585349                 48877.95    44711.20    44764.80   
72               466518217                 24998.12    44276.20    44359.10   
140              421008350                 41763.52    46895.90    47230.55   
235              235898642                 21925.60    48120.90    48246.20   
37               268261285                 28540.18    45060.55    45417.50   

     Bank_Low  Bank_Close  Bank_Shares Traded  Bank_Turnover (? Cr)  
169  48002.85    48125.10           224460146               8140.38  
159  47689.80    47761.65           183177683               8751.01  
180  45668.35    46188.65           305721773              10681.78  
147  47510.85    47732.30           193093079               9839.45  
150  47646.05    47870.90           189789200               7801.73  
..        ...         ...                 ...                   ...  
137  44254.60    44481.75           343168253              21570.23  
72   43983.75    44231.45           152511949               6418.26  
140  46653.65    47012.25           326064098              15573.44  
235  48028.70    48189.00           112159300               5867.57  
37   45042.60    45339.90           244924069              10612.41  

[196 rows x 12 columns]

In [93]:
m1.fit(
    scaler.fit_transform(x_train),
   scaler.fit_transform(y_train),
    epochs=500
)

Epoch 1/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2943 - loss: 0.2304
Epoch 2/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2871 - loss: 0.2252 
Epoch 3/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.2737 - loss: 0.2286 
Epoch 4/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3407 - loss: 0.2122 
Epoch 5/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.2610 - loss: 0.2239 
Epoch 6/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2547 - loss: 0.2186 
Epoch 7/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2827 - loss: 0.2216 
Epoch 8/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2443 - loss: 0.2156 
Epoch 9/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1669 - loss: 0.2063 
Epoch 10/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1702 - loss: 0.2185 
Epoch 11/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1528 - loss: 0.2155 
Epoch 12/500
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1862 - loss

In [94]:
m1.evaluate(scaler.fit_transform(x_test),scaler.fit_transform(y_test))

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2092 - loss: 0.0788  


[0.07976073771715164, 0.2199999988079071]

In [95]:
import numpy as np

In [96]:
testData=[21990.95,	22131.3	,21950.3,	22055.2,	265804411,	28717.71,	47555.5	,47868.7,	47313.35,	47421.1,	218854712,	10013.36]
y_pred=m1.predict(scaler.fit_transform(np.array([testData])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


In [97]:
scaler.fit_transform(y_test)

array([[0.189888  , 0.20513272, 0.2502921 , 0.24771612],
       [0.73960876, 0.75625812, 0.74206349, 0.73960926],
       [0.70690155, 0.69754812, 0.67492377, 0.67633688],
       [0.82058716, 0.81290592, 0.79896555, 0.83164051],
       [0.30501556, 0.3347277 , 0.3481662 , 0.33548174],
       [0.7297287 , 0.73257597, 0.75562822, 0.75749903],
       [0.34870911, 0.33687061, 0.38021857, 0.36791638],
       [0.23548889, 0.25021466, 0.27909578, 0.27066999],
       [0.74528503, 0.75054123, 0.6948719 , 0.68901869],
       [0.18721008, 0.19235596, 0.22505771, 0.23089816],
       [0.29245758, 0.28657816, 0.32719216, 0.32398682],
       [0.50428772, 0.50456837, 0.52664501, 0.5352832 ],
       [0.26503754, 0.29925218, 0.31909891, 0.33152541],
       [0.        , 0.        , 0.        , 0.        ],
       [0.57785797, 0.56715323, 0.3962127 , 0.39345984],
       [0.77774048, 0.8168028 , 0.80259183, 0.85106965],
       [0.48565674, 0.47202102, 0.48753242, 0.49067747],
       [0.54587555, 0.52749462,

In [98]:
y_pred

array([[0.238308  , 0.16440955, 0.18265869, 0.22597905]], dtype=float32)

In [99]:
scaler.data_max_

array([49262.  , 49529.35, 49123.6 , 49231.05])

In [100]:
scaler.inverse_transform(y_pred)

array([[44270.176, 43836.348, 43387.336, 43850.906]], dtype=float32)