In [3]:
import  tensorflow as tf
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df=pd.read_csv("../../data/NIFTY 50 - Minute data2.csv").dropna()

In [4]:
df.head()

date     open     high      low    close  volume  \
0  09-01-2015 09:15  8285.45  8295.90  8285.45  8292.10     0.0   
1  09-01-2015 09:16  8292.60  8293.60  8287.20  8288.15     0.0   
2  09-01-2015 09:17  8287.40  8293.90  8287.40  8293.90     0.0   
3  09-01-2015 09:18  8294.25  8300.65  8293.90  8300.65     0.0   
4  09-01-2015 09:19  8300.60  8301.30  8298.75  8301.20     0.0   

          next_date  next_open  next_high  next_low  next_close  next_volume  
0  09-01-2015 09:16    8292.60    8293.60   8287.20     8288.15          0.0  
1  09-01-2015 09:17    8287.40    8293.90   8287.40     8293.90          0.0  
2  09-01-2015 09:18    8294.25    8300.65   8293.90     8300.65          0.0  
3  09-01-2015 09:19    8300.60    8301.30   8298.75     8301.20          0.0  
4  09-01-2015 09:20    8300.50    8303.00   8298.60     8300.00          0.0

In [12]:
input_test_x=["open","high","low","close"]
input_test_y=["next_open","next_high"]

In [8]:
m1=tf.keras.Sequential(
    [
        tf.keras.layers.Dense(4, activation='relu'),
        tf.keras.layers.Dense(3, activation='relu'),
        tf.keras.layers.Dense(2, activation='sigmoid')
    ]
)
m1.build(input_shape=4)

In [9]:
m1.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
m1.compile(
    optimizer='adam',
    loss=tf.keras.losses.MeanAbsoluteError(
    reduction='sum_over_batch_size',
    name='mean_absolute_error'
),
    metrics=['accuracy']    
)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df[input_test_x], df[input_test_y], test_size= 0.2, random_state= 1)

In [15]:
m1.fit(
    scaler.fit_transform(x_train),
   scaler.fit_transform(y_train),
    epochs=5
)

Epoch 1/5
20919/20919 ━━━━━━━━━━━━━━━━━━━━ 15s 704us/step - accuracy: 0.4788 - loss: 0.0055
Epoch 2/5
20919/20919 ━━━━━━━━━━━━━━━━━━━━ 14s 680us/step - accuracy: 0.5832 - loss: 0.0054
Epoch 3/5
20919/20919 ━━━━━━━━━━━━━━━━━━━━ 14s 682us/step - accuracy: 0.6069 - loss: 0.0054
Epoch 4/5
20919/20919 ━━━━━━━━━━━━━━━━━━━━ 14s 670us/step - accuracy: 0.6084 - loss: 0.0054
Epoch 5/5
20919/20919 ━━━━━━━━━━━━━━━━━━━━ 15s 691us/step - accuracy: 0.6088 - loss: 0.0054


In [16]:
m1.evaluate(scaler.fit_transform(x_test),scaler.fit_transform(y_test))

5230/5230 ━━━━━━━━━━━━━━━━━━━━ 3s 524us/step - accuracy: 0.6856 - loss: 0.0054


[0.00533772399649024, 0.6861764192581177]

In [18]:
import numpy as np
testData=[21990.95,	22131.3	,21950.3, 22055.2]
y_pred=m1.predict(scaler.fit_transform(np.array([testData])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


In [19]:
y_pred

array([[0.03338346, 0.03337593]], dtype=float32)

In [20]:
scaler.fit_transform(y_test)

array([[0.32948236, 0.32886181],
       [0.64150931, 0.64105286],
       [0.07679137, 0.07591765],
       ...,
       [0.34563156, 0.34497895],
       [0.0865372 , 0.08574517],
       [0.20022981, 0.20148723]])

In [21]:
scaler.inverse_transform(y_pred)

array([[7356.6724, 7370.325 ]], dtype=float32)