In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [166]:
df= pd.read_csv("../../data/nifty2016-2024_withincrese.csv",parse_dates=True,index_col="Date")
df.head()


Open         High          Low        Close    Adj Close  \
Date                                                                          
04-01-2016  7924.549805  7937.549805  7781.100098  7791.299805  7791.299805   
05-01-2016  7828.399902  7831.200195  7763.250000  7784.649902  7784.649902   
06-01-2016  7788.049805  7800.950195  7721.200195  7741.000000  7741.000000   
07-01-2016  7673.350098  7674.950195  7556.600098  7568.299805  7568.299805   
08-01-2016  7611.649902  7634.100098  7581.049805  7601.350098  7601.350098   

            Volume   highorlow  isIncreseing  
Date                                          
04-01-2016  134700   43.750000             1  
05-01-2016  145200   47.049805             1  
06-01-2016  147100  105.050293             1  
07-01-2016  188900   10.299804             1  
08-01-2016  157400  -36.399903             0

In [38]:
df.dtypes

Open            float64
High            float64
Low             float64
Close           float64
Adj Close       float64
Volume            int64
highorlow       float64
isIncreseing      int64
dtype: object

In [21]:

df.isna().sum()

Open            0
High            0
Low             0
Close           0
Adj Close       0
Volume          0
highorlow       0
isIncreseing    0
dtype: int64

In [22]:
df["isIncreseing"].map(int)

Date
04-01-2016    1
05-01-2016    1
06-01-2016    1
07-01-2016    1
08-01-2016    0
             ..
03-05-2024    1
06-05-2024    1
07-05-2024    0
08-05-2024    1
09-05-2024    0
Name: isIncreseing, Length: 2055, dtype: int64

In [25]:
df[df["isIncreseing"] == 0].shape

(970, 8)

In [26]:
df[df["isIncreseing"] == 1].shape

(1085, 8)

In [28]:
df.head()

Open         High          Low        Close    Adj Close  \
Date                                                                          
04-01-2016  7924.549805  7937.549805  7781.100098  7791.299805  7791.299805   
05-01-2016  7828.399902  7831.200195  7763.250000  7784.649902  7784.649902   
06-01-2016  7788.049805  7800.950195  7721.200195  7741.000000  7741.000000   
07-01-2016  7673.350098  7674.950195  7556.600098  7568.299805  7568.299805   
08-01-2016  7611.649902  7634.100098  7581.049805  7601.350098  7601.350098   

            Volume   highorlow  isIncreseing  
Date                                          
04-01-2016  134700   43.750000             1  
05-01-2016  145200   47.049805             1  
06-01-2016  147100  105.050293             1  
07-01-2016  188900   10.299804             1  
08-01-2016  157400  -36.399903             0

In [95]:
x_test,y_test=df[-10:][["Open","High","Low","Close","Volume"]],df[-10:]["isIncreseing"]

In [35]:
print(x_test)
y_test

                   Open         High          Low        Close  Volume
Date                                                                  
25-04-2024  22316.90039  22625.94922  22305.25000  22570.34961  475000
26-04-2024  22620.40039  22620.40039  22385.55078  22419.94922  329900
29-04-2024  22475.55078  22655.80078  22441.90039  22643.40039  292000
30-04-2024  22679.65039  22783.34961  22568.40039  22604.84961  361900
02-05-2024  22567.84961  22710.50000  22567.84961  22648.19922  445900
03-05-2024  22766.34961  22794.69922  22348.05078  22475.84961  438100
06-05-2024  22561.59961  22588.80078  22409.44922  22442.69922  320300
07-05-2024  22489.75000  22499.05078  22232.05078  22302.50000  297800
08-05-2024  22231.19922  22368.65039  22185.19922  22302.50000  277400
09-05-2024  22224.80078  22307.75000  21932.40039  21957.50000  331300


Date
25-04-2024    1
26-04-2024    0
29-04-2024    1
30-04-2024    0
02-05-2024    1
03-05-2024    1
06-05-2024    1
07-05-2024    0
08-05-2024    1
09-05-2024    0
Name: isIncreseing, dtype: int64

In [97]:
x_train,y_train=df[:-10][["Open","High","Low","Close","Volume"]],df[:-10]["isIncreseing"]

In [81]:
print(x_train)
y_train

                    Open          High           Low         Close  Volume
Date                                                                      
04-01-2016   7924.549805   7937.549805   7781.100098   7791.299805  134700
05-01-2016   7828.399902   7831.200195   7763.250000   7784.649902  145200
06-01-2016   7788.049805   7800.950195   7721.200195   7741.000000  147100
07-01-2016   7673.350098   7674.950195   7556.600098   7568.299805  188900
08-01-2016   7611.649902   7634.100098   7581.049805   7601.350098  157400
...                  ...           ...           ...           ...     ...
18-04-2024  22212.349610  22326.500000  21961.699220  21995.849610  456900
19-04-2024  21861.500000  22179.550780  21777.650390  22147.000000  362500
22-04-2024  22336.900390  22375.650390  22198.150390  22336.400390  279300
23-04-2024  22447.050780  22447.550780  22349.449220  22368.000000  231500
24-04-2024  22421.550780  22476.449220  22384.000000  22402.400390  235900

[2045 rows x 5 columns]


Date
04-01-2016    1
05-01-2016    1
06-01-2016    1
07-01-2016    1
08-01-2016    0
             ..
18-04-2024    0
19-04-2024    1
22-04-2024    1
23-04-2024    1
24-04-2024    0
Name: isIncreseing, Length: 2045, dtype: int64

In [44]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM,Dense

In [128]:
model=Sequential()

In [117]:
def set_to_priodic(data , duration=10):
    sequencial_x_data=[]
    for i in range(len(data)-duration):
        sequencial_x_data.append(data[i:i+duration].to_numpy().tolist())
    return sequencial_x_data

In [ ]:
x_train=x_train.to_numpy()

In [118]:
sequencial_x_data = set_to_priodic(x_train)

In [129]:
model.add(LSTM(100, activation='relu', input_shape=(10, 5)))
model.add(Dense(1,activation="softmax"))

In [130]:
model.compile(
    loss="mse",
    optimizer="adam",
    metrics=["accuracy"]
)
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_4 (LSTM)                   │ (None, 100)            │        42,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 42,501 (166.02 KB)

 Trainable params: 42,501 (166.02 KB)

 Non-trainable params: 0 (0.00 B)

In [131]:
len(sequencial_x_data[0][0])

5

In [119]:
sequencial_x_data

[[[7924.549805, 7937.549805, 7781.100098, 7791.299805, 134700.0],
  [7828.399902, 7831.200195, 7763.25, 7784.649902, 145200.0],
  [7788.049805, 7800.950195, 7721.200195, 7741.0, 147100.0],
  [7673.350098, 7674.950195, 7556.600098, 7568.299805, 188900.0],
  [7611.649902, 7634.100098, 7581.049805, 7601.350098, 157400.0],
  [7527.450195, 7605.100098, 7494.350098, 7563.850098, 189000.0],
  [7587.200195, 7588.299805, 7487.799805, 7510.299805, 163900.0],
  [7557.899902, 7590.950195, 7425.799805, 7562.399902, 215200.0],
  [7467.399902, 7604.799805, 7443.799805, 7536.799805, 200800.0],
  [7561.649902, 7566.5, 7427.299805, 7437.799805, 197500.0]],
 [[7828.399902, 7831.200195, 7763.25, 7784.649902, 145200.0],
  [7788.049805, 7800.950195, 7721.200195, 7741.0, 147100.0],
  [7673.350098, 7674.950195, 7556.600098, 7568.299805, 188900.0],
  [7611.649902, 7634.100098, 7581.049805, 7601.350098, 157400.0],
  [7527.450195, 7605.100098, 7494.350098, 7563.850098, 189000.0],
  [7587.200195, 7588.299805, 748

In [99]:
sequencial_y_data=y_train[10:]

In [134]:
model.fit(np.asarray(sequencial_x_data),sequencial_y_data.to_numpy(),epochs=100)

Epoch 1/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5177 - loss: 0.4823
Epoch 2/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5219 - loss: 0.4781
Epoch 3/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5320 - loss: 0.4680
Epoch 4/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5225 - loss: 0.4775
Epoch 5/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5410 - loss: 0.4590
Epoch 6/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5245 - loss: 0.4755
Epoch 7/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5163 - loss: 0.4837
Epoch 8/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5362 - loss: 0.4638
Epoch 9/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5342 - loss: 0.4658
Epoch 10/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5398 - loss: 0.4602
Epoch 11/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5568 - loss: 0.4432
Epoch 12/100
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy:

In [142]:
len(set_to_priodic(df[-11:]))

1

In [ ]:
model.predict

In [165]:
len(set_to_priodic(df[-11:][["Open","High","Low","Close","Volume"]])[0][0])

5

In [150]:
model.predict(np.asarray(set_to_priodic(df[-11:][["Open","High","Low","Close","Volume"]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\ops\nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (1, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


array([[1.]], dtype=float32)

In [170]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [177]:
scale_sequence_X = scaler.fit_transform(df[:-10][["Open","High","Low","Close","Volume"]])

In [180]:
df.shape

(2055, 8)

In [181]:
scale_sequence_X.shape

(2045, 5)

In [182]:
scale_sequence_X

array([[0.05723106, 0.0573865 , 0.0602793 , 0.05199831, 0.0743788 ],
       [0.05112299, 0.0506305 , 0.05915296, 0.05157698, 0.0801767 ],
       [0.04855969, 0.04870883, 0.05649963, 0.04881139, 0.08122584],
       ...,
       [0.97279798, 0.97458636, 0.96999294, 0.97355414, 0.15422419],
       [0.97979545, 0.97915393, 0.97953988, 0.97555624, 0.12782993],
       [0.97817553, 0.98098974, 0.98172002, 0.9777358 , 0.13025953]])

In [187]:
train_scale_data_x=np.asarray(set_to_priodic(pd.DataFrame(scale_sequence_X)))

In [192]:
model2=Sequential([
    LSTM(100, activation='relu', input_shape=(10, 5)),
    Dense(1,activation="softmax")
])
model2.compile(
    loss="mse",
    optimizer="adam",
    metrics=["accuracy"]
)
model2.summary()

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_7 (LSTM)                   │ (None, 100)            │        42,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 42,501 (166.02 KB)

 Trainable params: 42,501 (166.02 KB)

 Non-trainable params: 0 (0.00 B)

In [194]:
model2.fit(train_scale_data_x,sequencial_y_data.to_numpy(),epochs=20)

Epoch 1/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5311 - loss: 0.4689
Epoch 2/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5307 - loss: 0.4693
Epoch 3/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5311 - loss: 0.4689
Epoch 4/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5244 - loss: 0.4756
Epoch 5/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5241 - loss: 0.4759
Epoch 6/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5359 - loss: 0.4641
Epoch 7/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5284 - loss: 0.4716
Epoch 8/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5020 - loss: 0.4980
Epoch 9/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5176 - loss: 0.4824
Epoch 10/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5433 - loss: 0.4567
Epoch 11/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5261 - loss: 0.4739
Epoch 12/20
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5272 - lo

In [195]:
model2.predict(np.asarray(set_to_priodic(df[-11:][["Open","High","Low","Close","Volume"]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step


c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\ops\nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (1, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


array([[1.]], dtype=float32)