In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("../data/NIFTY 50 - Minute data1.csv")
df.head()

date     open     high      low    close  volume
0  2015-01-09 09:15:00  8285.45  8295.90  8285.45  8292.10       0
1  2015-01-09 09:16:00  8292.60  8293.60  8287.20  8288.15       0
2  2015-01-09 09:17:00  8287.40  8293.90  8287.40  8293.90       0
3  2015-01-09 09:18:00  8294.25  8300.65  8293.90  8300.65       0
4  2015-01-09 09:19:00  8300.60  8301.30  8298.75  8301.20       0

In [5]:
df.isnull().sum()

date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [6]:
# Splitting the data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=["date","close","volume"]), df["close"], test_size= 0.3, random_state= 1)

In [7]:
x_train.head()

open      high       low
430717  11046.80  11048.05  11046.25
645638  17725.85  17728.95  17721.70
195877   8936.85   8939.65   8936.85
815237  19124.50  19125.20  19121.05
291269  10402.95  10403.10  10398.85

In [8]:
y_train

430717    11046.75
645638    17722.45
195877     8938.40
815237    19124.40
291269    10398.85
            ...   
491263     9338.40
791624    19740.30
470924    12154.10
491755     9216.90
128037     8188.65
Name: close, Length: 585729, dtype: float64

In [9]:
from sklearn.linear_model import LinearRegression

l1=LinearRegression()

In [10]:
l1.fit(x_train,y_train)

LinearRegression()

In [11]:
score=l1.score(x_test,y_test)

In [12]:
score

0.9999997854483164

In [13]:
import numpy as np

In [14]:
l1.predict(np.array([[21433.10,21763.25,21429.60]]))

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([21692.28997011])

In [15]:
l1.predict(np.array([[21775.25,21813.05,21501.8]]))

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([21578.53478586])

In [16]:
l2=LinearRegression()

In [17]:
x_train["open"]

430717    11046.80
645638    17725.85
195877     8936.85
815237    19124.50
291269    10402.95
            ...   
491263     9339.55
791624    19737.70
470924    12153.15
491755     9212.25
128037     8190.05
Name: open, Length: 585729, dtype: float64

In [18]:
# Splitting the data into train and test

x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=["date","high","low","close","volume"]), df["close"], test_size= 0.3, random_state= 1)

In [19]:
x_train

open
430717  11046.80
645638  17725.85
195877   8936.85
815237  19124.50
291269  10402.95
...          ...
491263   9339.55
791624  19737.70
470924  12153.15
491755   9212.25
128037   8190.05

[585729 rows x 1 columns]

In [20]:
l2.fit(x_train,y_train)

LinearRegression()

In [21]:
score=l2.score(x_test,y_test)

In [22]:
score

0.999998460791138

In [23]:
l2.predict(np.array([[22033.30]]))

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([22033.31435321])

In [24]:
l2.predict(np.array([[22037.40]]))

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([22037.41437162])

In [25]:
l2.predict(np.array([[22037.55]]))

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([22037.56437229])

In [26]:
df.head()

date     open     high      low    close  volume
0  2015-01-09 09:15:00  8285.45  8295.90  8285.45  8292.10       0
1  2015-01-09 09:16:00  8292.60  8293.60  8287.20  8288.15       0
2  2015-01-09 09:17:00  8287.40  8293.90  8287.40  8293.90       0
3  2015-01-09 09:18:00  8294.25  8300.65  8293.90  8300.65       0
4  2015-01-09 09:19:00  8300.60  8301.30  8298.75  8301.20       0

In [27]:
temp=df.copy()

In [28]:
temp2=temp.copy()

In [29]:
temp2.head()

date     open     high      low    close  volume
0  2015-01-09 09:15:00  8285.45  8295.90  8285.45  8292.10       0
1  2015-01-09 09:16:00  8292.60  8293.60  8287.20  8288.15       0
2  2015-01-09 09:17:00  8287.40  8293.90  8287.40  8293.90       0
3  2015-01-09 09:18:00  8294.25  8300.65  8293.90  8300.65       0
4  2015-01-09 09:19:00  8300.60  8301.30  8298.75  8301.20       0

In [30]:
temp2=temp2.drop(index=0)

In [31]:
pd.concat([temp, temp2], axis=1, join='inner')

date      open      high       low     close  volume  \
1       2015-01-09 09:16:00   8292.60   8293.60   8287.20   8288.15       0   
2       2015-01-09 09:17:00   8287.40   8293.90   8287.40   8293.90       0   
3       2015-01-09 09:18:00   8294.25   8300.65   8293.90   8300.65       0   
4       2015-01-09 09:19:00   8300.60   8301.30   8298.75   8301.20       0   
5       2015-01-09 09:20:00   8300.50   8303.00   8298.60   8300.00       0   
...                     ...       ...       ...       ...       ...     ...   
836752  2024-01-25 15:25:00  21376.55  21378.90  21372.75  21377.95       0   
836753  2024-01-25 15:26:00  21376.55  21386.10  21375.80  21384.20       0   
836754  2024-01-25 15:27:00  21384.75  21401.75  21381.30  21394.15       0   
836755  2024-01-25 15:28:00  21392.70  21396.25  21384.25  21395.70       0   
836756  2024-01-25 15:29:00  21391.75  21391.95  21367.40  21370.75       0   

                       date      open      high       low     close  volume  
1       2015-01-09 09:16:00   8292.60   8293.60   8287.20   8288.15       0  
2       2015-01-09 09:17:00   8287.40   8293.90   8287.40   8293.90       0  
3       2015-01-09 09:18:00   8294.25   8300.65   8293.90   8300.65       0  
4       2015-01-09 09:19:00   8300.60   8301.30   8298.75   8301.20       0  
5       2015-01-09 09:20:00   8300.50   8303.00   8298.60   8300.00       0  
...                     ...       ...       ...       ...       ...     ...  
836752  2024-01-25 15:25:00  21376.55  21378.90  21372.75  21377.95       0  
836753  2024-01-25 15:26:00  21376.55  21386.10  21375.80  21384.20       0  
836754  2024-01-25 15:27:00  21384.75  21401.75  21381.30  21394.15       0  
836755  2024-01-25 15:28:00  21392.70  21396.25  21384.25  21395.70       0  
836756  2024-01-25 15:29:00  21391.75  21391.95  21367.40  21370.75       0  

[836756 rows x 12 columns]

In [32]:
df=pd.read_csv("../data/NIFTY 50 - Minute data2.csv")
df.head()

date     open     high      low    close  volume  \
0  09-01-2015 09:15  8285.45  8295.90  8285.45  8292.10     0.0   
1  09-01-2015 09:16  8292.60  8293.60  8287.20  8288.15     0.0   
2  09-01-2015 09:17  8287.40  8293.90  8287.40  8293.90     0.0   
3  09-01-2015 09:18  8294.25  8300.65  8293.90  8300.65     0.0   
4  09-01-2015 09:19  8300.60  8301.30  8298.75  8301.20     0.0   

          next_date  next_open  next_high  next_low  next_close  next_volume  
0  09-01-2015 09:16    8292.60    8293.60   8287.20     8288.15          0.0  
1  09-01-2015 09:17    8287.40    8293.90   8287.40     8293.90          0.0  
2  09-01-2015 09:18    8294.25    8300.65   8293.90     8300.65          0.0  
3  09-01-2015 09:19    8300.60    8301.30   8298.75     8301.20          0.0  
4  09-01-2015 09:20    8300.50    8303.00   8298.60     8300.00          0.0

In [33]:
df=df.dropna()

In [34]:
l3=LinearRegression()

In [35]:
# Splitting the data into train and test

x_train, x_test, y_train, y_test = train_test_split(df[["open","high","low"	,"close","next_open"]], df[["next_high","next_low"]], test_size= 0.3, random_state= 1)

In [36]:
l3.fit(x_train,y_train)

LinearRegression()

In [37]:
score=l3.score(x_test,y_test)

In [38]:
score

0.9999993297367535

In [45]:
l3.predict(np.array([[21990.95,22131.30,21950.30,22055.20,22024.95]]))

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[22074.40363333, 21975.84040383]])

In [40]:
l3.predict(np.array([[22037.40,22052.55,22036.75,22036.75,22037.55]]))

c:\Users\baps\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[22042.44444369, 22030.8701423 ]])

### random forest

In [41]:
import tensorflow as tf

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scaler = MinMaxScaler()

In [44]:
scaler.fit_transform(x_train,y_train)

array([[0.1740531 , 0.17263925, 0.17400756, 0.17294517, 0.17294379],
       [0.27498609, 0.27364359, 0.27498813, 0.27404593, 0.27402024],
       [0.71222706, 0.7116012 , 0.71221373, 0.71190447, 0.71191113],
       ...,
       [0.34742201, 0.34637366, 0.34746836, 0.34664429, 0.34662183],
       [0.15487282, 0.15370995, 0.15481854, 0.15408015, 0.15413864],
       [0.08794644, 0.08625568, 0.08785503, 0.08666763, 0.08667676]])